version: '3'

services:
  color_classifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_color_classifier
    volumes:
      - ./:/app
      - avito_weights:/app/weights
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --no-browser
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  avito_weights:
    driver: local 